const data=window.MAHABBAH;
const dialog=document.querySelector('#detail-dialog');
const content=document.querySelector('#dialog-content');
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
let lastFocus=null;
const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
function openModal(html){lastFocus=dialog.open?lastFocus:document.activeElement;content.innerHTML=html;if(!dialog.open)dialog.showModal();document.body.classList.add('modal-open');dialog.scrollTop=0;dialog.querySelector('.close-modal').focus();}
function closeModal(){dialog.close();}
dialog.querySelector('.close-modal').addEventListener('click',closeModal);
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');lastFocus?.focus();});
function contact(subject=''){const message=data.contact.consultationMessage+(subject?' Saya ingin mengetahui lebih lanjut tentang '+subject+'.':'');if(/^\d{8,15}$/.test(data.contact.number)){window.open('https://wa.me/'+data.contact.number+'?text='+encodeURIComponent(message),'_blank','noopener,noreferrer');return;}openModal(`<div class="contact-notice"><span aria-hidden="true">💬</span><h2 id="dialog-title">Mari Mulai Percakapan</h2><p>Nomor WhatsApp admin Mahabbah belum tersedia pada versi pratinjau ini. Tautan konsultasi akan aktif setelah nomor resmi ditambahkan.</p><div class="contact-message">${esc(message)}</div><button class="button" id="copy-message">Salin Pesan Konsultasi</button><p class="copy-status" role="status"></p></div>`);document.querySelector('#copy-message').onclick=async()=>{try{await navigator.clipboard.writeText(message);document.querySelector('.copy-status').textContent='Pesan tersalin. Simpan untuk menghubungi admin nanti.';}catch{document.querySelector('.copy-status').textContent='Silakan pilih dan salin pesan di atas secara manual.';}};}
function programDetail(id){const p=data.programs.find(x=>x.id===id);if(!p)return;const facts=[['Usia',p.age],['Level',p.level],['Mode',p.mode],['Lokasi',p.location],['Jadwal',p.schedule.join(' · ')],['Durasi',p.duration],['Frekuensi',p.frequency],['Kapasitas',p.maxStudents?'Maksimal '+p.maxStudents+' santri (sementara)':'Konfirmasi admin'],['Biaya',p.price?money(p.price):'Akan dikonfirmasi'],['Kelas percobaan',p.trial]];openModal(`<div class="modal-cover">${p.image?`<img src="${p.image}" alt="Ilustrasi AI kegiatan belajar Al-Qur’an">`:`<span>${p.icon}</span>`}</div><h2 id="dialog-title" class="modal-title">${p.name}</h2><p class="modal-subtitle">${p.tagline}</p><p>${p.description}</p><p class="modal-data-note">Informasi sementara untuk pratinjau. Jadwal, biaya, lokasi, serta ketersediaan program perlu dikonfirmasi dengan admin.</p><dl class="detail-grid">${facts.map(([t,v])=>`<div><dt>${t}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl><div class="detail-list">${[['Manfaat belajar',p.benefits],['Materi pembelajaran',p.curriculum],['Arah perkembangan',p.outcomes]].map(([t,a])=>`<h3>${t}</h3><ul>${a.map(v=>`<li>${v}</li>`).join('')}</ul>`).join('')}</div><button class="button full modal-cta" data-wa="${esc(p.name)}">Konsultasi ${p.name} via WhatsApp</button>`);}
function galleryDetail(id){const g=data.gallery.find(x=>x.id===id);if(!g)return;openModal(`${g.image?`<img class="lightbox-image" src="${g.image}" alt="${g.alt}">`:`<div class="lightbox-placeholder" role="img" aria-label="${g.alt}">${g.icon}</div>`}<p class="eyebrow" style="margin-top:24px">${g.category}</p><h2 id="dialog-title" class="modal-title">${g.title}</h2><p>${g.caption}</p>`);}
function donationDetail(id){const d=data.donations.find(x=>x.id===id);if(!d)return;openModal(`<div class="modal-cover"><span>${d.icon}</span></div><p class="eyebrow">${d.category}</p><h2 id="dialog-title" class="modal-title">${d.title}</h2><p>${d.description}</p><p class="modal-data-note">Rincian kampanye masih berupa contoh. Belum ada pembayaran atau transfer yang diproses melalui website ini.</p>${d.target?`<dl class="detail-grid"><div><dt>Contoh target</dt><dd>${d.targetUnit?d.target+' '+d.targetUnit:money(d.target)}</dd></div><div><dt>Terkumpul</dt><dd>Data belum tersedia</dd></div></dl>`:''}<div class="detail-list"><h3>Tujuan program</h3><ul>${d.purpose.map(x=>`<li>${x}</li>`).join('')}</ul></div>${d.suggestedAmounts.length?`<h3>Pilih nominal sedekah</h3><div class="amounts" role="group" aria-label="Nominal sedekah">${d.suggestedAmounts.map(n=>`<button class="filter" aria-pressed="false" data-amount="${n}">${money(n)}</button>`).join('')}</div><p id="amount-status" class="copy-status" role="status">Nominal bersifat pilihan, bukan pembayaran.</p>`:''}<div class="detail-list"><h3>Dokumentasi & kabar terbaru</h3><p>Foto lokasi, kegiatan, dan pembaruan pengumpulan akan ditambahkan setelah tersedia.</p></div><button id="donation-contact" class="button full donation-button modal-cta" data-wa="${esc(d.title)}">Tanyakan ${d.cta} via WhatsApp</button>`);content.querySelectorAll('[data-amount]').forEach(b=>b.onclick=()=>{content.querySelectorAll('[data-amount]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});document.querySelector('#amount-status').textContent='Pilihan nominal: '+money(Number(b.dataset.amount));document.querySelector('#donation-contact').dataset.wa=d.title+' dengan nominal '+money(Number(b.dataset.amount));});}
function filter(type,value){document.querySelectorAll(`[data-filter="${type}"]`).forEach(b=>{b.classList.toggle('active',b.dataset.value===value);b.setAttribute('aria-pressed',String(b.dataset.value===value));});const parent=type==='program'?document.querySelector('#program-grid'):document.querySelector('.gallery-grid');let count=0;parent.querySelectorAll('[data-category]').forEach(card=>{const show=value==='Semua'||card.dataset.category.split(',').includes(value);card.hidden=!show;if(show)count++;});if(type==='program')document.querySelector('#program-empty').hidden=count>0;else parent.classList.toggle('filtered',value!=='Semua');}
document.addEventListener('click',event=>{const wa=event.target.closest('[data-wa]');if(wa){contact(wa.dataset.wa);return;}const p=event.target.closest('[data-program]');if(p){programDetail(p.dataset.program);return;}const g=event.target.closest('[data-gallery]');if(g){galleryDetail(g.dataset.gallery);return;}const d=event.target.closest('[data-donation]');if(d){donationDetail(d.dataset.donation);return;}const f=event.target.closest('[data-filter]');if(f){filter(f.dataset.filter,f.dataset.value);return;}const footer=event.target.closest('[data-footer-filter]');if(footer)filter('program',footer.dataset.footerFilter);});
const menu=document.querySelector('.menu'),nav=document.querySelector('nav');menu.onclick=()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Tutup menu':'Buka menu');nav.classList.toggle('open',open);};nav.querySelectorAll('a').forEach(a=>a.onclick=()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Buka menu');});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.focus();}});
const floating=document.querySelector('.floating-wa');const observer=new IntersectionObserver(entries=>{for(const e of entries)floating.classList.toggle('is-hidden',e.isIntersecting);},{threshold:.05});observer.observe(document.querySelector('#konsultasi'));
